### PR TITLE
Create harbour-quickddit-sv.ts

### PR DESCRIPTION
**Pull request by eson57**
Here's a Swedish translation if wanted. Thanks for the app!

### CODE REVIEW

**Comment by accumulator** [comment]
Thanks for the translation! 
Unfortunately translations are not working yet in Quickddit, I've spend quite some time to get it working, but to no success yet.. I'll merge it and upload to Transifex once I have some time again to work on translation support.

**Comment by eson57** [comment]
What on earth are you talking about? Swedish translation is working perfect on my Xperia X, SFOS 2.1.3.7

screen_20171228_001

**Comment by accumulator** [comment]
Ok that is truly a suprise :)

Is this tied to the Phone's global language setting? The phone has no global dutch language, so I've been testing with setting language on app level, but that I haven't got to work..

**Comment by d9h20f** [comment]
It does: https://openrepos.net/content/martonmiklos/nederlands-community-translation-jolla

Some of the community translations, including this one, will soon™ be part of the basic Sailfish package, too.

**Comment by accumulator** [comment]
I've uploaded your translation to the Transifex Quickddit space. If you're interested I can add you as a translator there?

**Comment by eson57** [comment]
Yes, please do! That will make maintenance easier.
So the lack of dutch language on your phone was the explanation. I could never have guessed.  :)

**Pull request merged**
