### PR TITLE
Sailfish: Accounts Navigation flow refactor

### PR DESCRIPTION
**Pull request by Thaodan**
Points addressed with this PR:
- [x] Rename AppSettings to Settings as the App in AppSetting seems redundant
- [x] Move all account related setting to AccountsPage
- [ ] Improve/Add hints how to create account when there are no accounts
- [ ] Prompt how to create account by showing the Accountspage/WelcomePage on initial start

So far only the last two commits belong to this PR.

### CODE REVIEW

**Comment by Thaodan** [comment]
This wasn't fully done, feel free to provide more feedback..

**Comment by accumulator** [comment]
Aah ok, that explains a few issues I encountered. I saw the PR earlier and thought it was ready. Thanks for the improvements. Feel free to rebase/force-push and reopen this PR

**Comment by accumulator** [comment]
I was a bit in a rush, as I only recently got notified that login wasn't working anymore (didn't notice myself as I didn't need to login in ages), and the required change for that was already in your branch.

As for the delta for `sailfish/rpm/harbour-quickddit.spec` in b7c7a8c7cb1a7abcea21e48c1058053dab6efb22, I include the entire `%{_datadir}/*` because I'm building two variants; a harbour compliant version and a standard version that includes lipstick notification file, which is (AFAIK) not allowed still on harbour.

**Comment by Thaodan** [comment]
accumulator ***@***.***> writes:

> As for the delta for `sailfish/rpm/harbour-quickddit.spec` in
> b7c7a8c7cb1a7abcea21e48c1058053dab6efb22, I include the entire
> `%{_datadir}/*` because I'm building two variants; a harbour compliant

That is wrong, you can add the path in the data dir instead for the
non-harbour build, adding the entire datadir is a hack.

To differentiate between harbour and non-harbour add this on to of the
spec:
`%bcond_without harbour`

Then add either `%if %{with harbour}` or `%if %{without harbour}` in the
cases you want differentiate.

E.g.
```
%if %{without harbour}
<not harbour stuff>
%endif
```

> version and a standard version that includes lipstick notification
> file, which is (AFAIK) not allowed still on harbour.

This is not true. Shipping notification category files is not allowed
however these are mostly redundant now.

I have one pending comment that will get red of the need to have the
file around.

Notifications work afterwards except that the Dbus service won't work
inside the standbox as Dbus services are not exported until you define a
profile and then you can spawn a service that matches the object path:
<tld><organization><appname>.

**Comment by accumulator** [comment]
> To differentiate between harbour and non-harbour add this on to of the
> spec:

I don't have the time or interest to get acquainted with .spec files. If you think it helps, then patches welcome.

> Shipping notification category files is not allowed
> however these are mostly redundant now. 
 
Also here, no time to adapt this to current sailfish, so feel free to patch :)

patches welcome, I guess

**Pull request merged**
