### PR TITLE
Ubuntu touch port update

### PR DESCRIPTION
**Pull request by dano6**
This brings numbers of improvements, UI redesign and multireddit support

### CODE REVIEW

**Comment by dano6** [comment]
Still a lot of things to do, but this could be first release. I am getting short pause now, but will be back soon

**Comment by dano6** [comment]
Relased in OpenStore https://open-store.io/app/quickddit

**Comment by szopin** [comment]
>add DonatePage???
lol, somehow not surprised

**Comment by szopin** [comment]
Just to be clear I'm  not laughing at all android devs here (got the priorities straight), but renaming qml values and adding that with no intention of spreading to original devs? Yeah, fucking kek

**Comment by szopin** [comment]
And just to be clear: you have brought literally 0 things back to the community, you're cashing in on other peoples' work 100% and all you did was repackage (muh qml renames), a fucking joke. At least let the owner of the repo pull your pull request and not abuse the powers he gave to you to do a quickie, I'm out have a wonderful day

**Pull request merged**
