### PR TITLE
Inintial ubuntu touch support

### PR DESCRIPTION
**Pull request by dano6**
This PR brings initial support for Ubuntu Touch. Some minor changes was done for backend, please check if Sailfish builds fine. Minimal version of  QT is 5.9, using Qt Quick Controls 2. Ubuntu specific API was not yet used (notifications, sharing, uploading and downloading files), as I am not sure yet how to separate it from other code. I want to keep code buildable for any Linux distro. 
I am committing myself to maintain code in ubuntu-touch folder, any help is welcomed. 
I would love to publish app latter in OpenStore, if you are OK with that.

Features not implemented yet:

- Multireddit support
- Search for posts
- Imgur gallery 
- Video playback on phones (youtube-dl not yet packaged)
- Submit new links and self-posts
- Notifications, sharing
- Translation support
- Watching clipboard for reddit links
- Option to use TOR (not sure how hard it would be)
- Planned more UI polishing
- And more...

Build instructions for PC:
- Install https://github.com/ubports/qqc2-suru-style/ (5.12 or higher use 5.12 branch)
- Open project in QtCreator and run

Build instructions for Ubuntu Touch:
- install clickable with `pip install clickable-ut` 
- Go to Quickddit folder
- run command `clickable -c ubuntu-touch/clickable.json` ( `clickable -c ubuntu-touch/clickable.json desktop` to run in docker on PC)

### CODE REVIEW

**Comment by dano6** [comment]
@accumulator can you please give me some contact? I would love to ask couple questions.

**Comment by accumulator** [comment]
Hi @dano6 
You can email me at quickddit[at]outrightsolutions.nl for any questions you have!

> Some minor changes was done for backend, please check if Sailfish builds fine.

From a quick glance it looks like the backend changes will compile fine. I can test later this week.

> Ubuntu specific API was not yet used (notifications, sharing, uploading and downloading files), as I am not sure yet how to separate it from other code. I want to keep code buildable for any Linux distro.

There is some platform specific code in **qmlutils.cpp** in the backend code tree, which is mostly Qt4 vs Qt5 #ifdefs and some UI scaling trickery that makes various sailfish device ports look similar, but there's also platform specific stuff that should really be moved out of the backend tree at some point :)

For now, if you can #ifdef it into qmlutils.cpp that's fine, or if you want to add code in /ubuntu-touch/src and make it available to QML scope that's also fine, but keep in mind that there should be no direct dependency on platform specific code from the backend code.

> I would love to publish app latter in OpenStore, if you are OK with that

Please do! :)

**Comment by accumulator** [comment]
Also,

- sharing is not implemented yet in sailfish, it needs a platform specific (nemo) component
- For TOR you don't need to do anything. Just have a useTor property on your Settings QObject.
- translations is currently platform specific unfortunately, unless everything is refactored to ID-based translations. Aalso adding translations in the building process is probably (slightly?) different. I can look into adding the ubuntu port translations to transifex when you have the boilerplate in place.
- clipboard is pure Qt5, so probably already working, just connect to QMLUtils::clipboardChanged signal

**Comment by accumulator** [comment]
I tried it out, it looks very good. Also quite some functionality already.
Very different style, but I could find my way around.

Love the hot search bar for subreddits!

**Comment by dano6** [comment]
Thanks for all hints and the merge! 
Also, I wanted to say that the backend is well written and easy to work with.

> I tried it out, it looks very good. Also quite some functionality already.
Very different style, but I could find my way around.
Love the hot search bar for subreddits!

I am glad you like it.

**Pull request merged**
