### PR TITLE
Sailfish Packaging improvements

### PR DESCRIPTION
**Pull request by Thaodan**
+ sailfish: Allow passing reddit credentials during build
+ sailfish: Remove spectacle leftovers

### CODE REVIEW

**Comment by Thaodan** [comment]
I moved the Qt Creator part of this change to a shared pri file.

**Comment by accumulator** [comment]
Thanks, first impression is it looks good. This week unfortunately I don't have time to test..

**Comment by Thaodan** [comment]
Can you look into this again?

**Comment by accumulator** [comment]
> Can you look into this again?

I tried installing the Sailfish SDK as my old install got broken during an update. However I'm getting SSL errors on the online installer and dependency errors with the offline installer, so can't test right now.

**Comment by Thaodan** [comment]
Why did you revert f682373c8482c8ae7153b6f9086f20f886df9318? You break packaging on the obs..

**Pull request merged**
