### PR TITLE
Update harbour-quickddit-sv.ts

### PR DESCRIPTION
**Pull request by eson57**
new string translated

### CODE REVIEW

**Comment by accumulator** [comment]
Hi eson57. Thanks for the improvement, but I always fetch the latest translations from Transifex before making a release, so PR's are not very handy, as the change could be overwritten in the future from Transifex..

**Comment by eson57** [comment]
OK, noted. With 700+ translations to maintain, I sometimes forget who is on transifex and who is not. ;)

**Comment by accumulator** [comment]
Maybe I should document this in a contributor guide.. :)

**Comment by eson57** [comment]
A short note in the about page should be enough, I think.

**Pull request closed without merging**
